[build]
  command = "npm run build" # Comando para construir tu aplicaci贸n Vue.js
  publish = "public" # Directorio donde se encuentra la versi贸n compilada de tu aplicaci贸n

[[redirects]] # Configuraci贸n de redireccionamiento para SPA
  from = "/*" # Redirige todas las rutas a index.html
  to = "/index.html"
  status = 200
